const { chromium } = require('playwright');
const fs = require('fs');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROME_EXECUTABLE || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'], proxy: process.env.HTTPS_PROXY ? { server: process.env.HTTPS_PROXY, bypass: 'localhost,127.0.0.1' } : undefined });
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.DUEDESK_TEST_URL || 'http://127.0.0.1:8080', { waitUntil: 'networkidle' });
  await page.locator('flt-semantics-placeholder').waitFor({ state: 'attached', timeout: 60000 });
  await page.locator('flt-semantics-placeholder').evaluate(e => e.click());
  const demo = page.getByRole('button', { name: 'Continue in demo mode', exact: true });
  await demo.waitFor({ timeout: 60000 });
  await demo.click();
  await page.getByRole('button', { name: 'Skip', exact: true }).click();
  await page.getByText('Due overview', { exact: true }).waitFor({ timeout: 30000 });
  await page.screenshot({ path: 'artifacts/browser-dashboard.png' });
  await page.reload({ waitUntil: 'networkidle' });
  const placeholder = page.locator('flt-semantics-placeholder');
  if (await placeholder.count()) await placeholder.evaluate(e => e.click());
  await page.getByText('Due overview', { exact: true }).waitFor({ timeout: 30000 });
  if (errors.length) throw new Error(errors.join('\n'));
  fs.writeFileSync('artifacts/verification/browser-smoke.log', 'PASS: Web startup, accessible demo entry, onboarding skip, dashboard, and persisted session after reload. No uncaught browser errors.\n');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
